### ISSUE TITLE
asdcplib-2.10.31  Error

### ISSUE THREAD

**Issue by youngwug** [fd00/yacp#17]
Thank you for your unlimited sharing.
Error appears as attached document.
I have tried a few things but it does not work.
Please tell me how to fix it.
[error.txt](https://github.com/fd00/yacp/files/2705970/error.txt)

**Comment by fd00** [comment]
> checking for ASDCPLIB... no
> configure: error: Package requirements (openssl expat xerces-c) were not met:
> 
> No package 'openssl' found
> No package 'expat' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables ASDCPLIB_CFLAGS
> and ASDCPLIB_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> *** ERROR: configure failed

Please install openssl and expat.

**Comment by youngwug** [comment]
cygcheck -c
expat                                   2.2.6-1                         OK
expat-debuginfo                         2.2.6-1                         OK
openssl                                 1.0.2p-1                        OK
xerces-c-debuginfo                      3.1.4-1                         OK

Do I have to do something else?

**Comment by fd00** [comment]
Sorry, please install openssl-devel and libexpat-devel.

**Comment by youngwug** [comment]
Thank You.
Fix Compile.

young@DESKTOP-D9J7LJ8 /cygdrive/c/Users/young/Downloads/asdcplib/asdcplib-2.10.31
$ asdcp-test -h
      2 [main] asdcp-test (8876) C:\Users\young\Downloads\cygport\2719_win10_cygport\asdcp-test.exe: *** fatal error - cygheap base mismatch detected - 0x18031D410/0x1802F3408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.

but
win10 CMD
asdcp-test -h 
---
---
OK

Thank you for your unlimited sharing.(again)
