### ISSUE TITLE
Sorry, we had to truncate this directory

### ISSUE THREAD

**Issue by cup** [fd00/yacp#20]
when you go here:

https://github.com/fd00/yacp

you get this message:

> Sorry, we had to truncate this directory to 1,000 files. 1,180 entries were
> omitted from the list.

so instead of this:

~~~
a-package-1/README
a-package-2/README
b-package-1/README
b-package-2/README
~~~

you can split like this:

~~~
a/a-package-1/README
a/a-package-2/README
b/b-package-1/README
b/b-package-2/README
~~~

Notice that Debian uses similar tactic:

http://cdn-fastly.deb.debian.org/debian/pool/main

**Comment by fd00** [comment]
I don't really want to split at this time.

Because I should fix my utility ([xezat](https://github.com/fd00/xezat)) and It has an impact on [repology](https://repology.org/) at least.
