### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by cup** [fd00/yacp#21]
please and thank you

**Comment by fd00** [comment]
I'm requesting to cygwinports.
- https://github.com/cygwinports/ruby/pull/3

**Comment by cup** [comment]
https://github.com/cygwinports/ruby/issues/1
https://github.com/cygwinports/ruby/pull/3
https://github.com/fd00/yacp/issues/21

**Comment by cup** [comment]
https://github.com/cygwinports/ruby/issues/1
https://github.com/cygwinports/ruby/pull/2
https://github.com/cygwinports/ruby/pull/3
https://github.com/fd00/yacp/issues/21

**Comment by fd00** [comment]
official package released
* https://cygwin.com/packages/x86_64/ruby/ruby-2.6.3-1
