### ISSUE TITLE
How do I build and use the ports in this repo?

### ISSUE THREAD

**Issue by dgonyier** [fd00/yacp#29]
I would like to install fapg (and required uriparser) to my local Cygwin install. I am not sure how to use this repository to do that.

The README files for the various ports in this repo say to use `setup.exe` to download the XYZ-src.tar.gz files to then build them locally. I don't see either of the packages I am interested in the package list of the default cygwin mirror I use.

Do I have to change `setup.exe` to use a certain mirror to find these non-standard packages for Cygwin?

Thanks.

**Comment by fd00** [comment]
yacp provides recipes only.
If you need a package, you will need to build it yourself.

```
$ git clone https://github.com/fd00/yacp.git
$ cd yacp/uriparser
$ cygport uriparser-X.Y.Z-1bl1.cygport all
$
```

If the build is successful, the package will be generated under dist.

For more information, please translate this website and check the instructions.
- https://fd0.hatenablog.jp/entry/2020/11/01/001043

**Comment by dgonyier** [comment]
I did manage to get ```fapg.exe``` to build and run succesfully.

Trying  ```cygport foo.cygport all``` didn't work so I performed the steps individually (fetch, prep, compile, install). 

Also I discovered that ```uriparser``` has a build dependency on ```googletest```, which is not mentioned in the README file

**Comment by fd00** [comment]
Fixed https://github.com/fd00/yacp/commit/f30a0d454b7a90144e1462363904e69d77563ad3

**Comment by fd00** [comment]
If there are no other problems, I would like to close it.

**Comment by dgonyier** [comment]
You can close. Thanks for your help.
