### ISSUE TITLE
libbuspirate 0.5.0 available

### ISSUE THREAD

**Issue by micwoj92** [fd00/yacp#31]
Currently in this repo: 0.4.0

**Comment by fd00** [comment]
Cygwin's official autoconf is not up to date, so it cannot be built.

```
>>> Compiling libbuspirate-0.5.0-1bl1.x86_64
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
configure.ac:6: error: Autoconf version 2.71 or higher is required
configure.ac:6: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 63
aclocal-1.16: error: echo failed with exit status: 63
autoreconf-2.69: aclocal failed with exit status: 63
*** ERROR: autoreconf failed
```

We need to wait for an update.

**Comment by micwoj92** [comment]
@fd00 I've seen autoconf 2.71 is now available, I get this when running latest setup.
![image](https://user-images.githubusercontent.com/45581170/147722001-8035dfff-4232-4120-9e47-7c894fdd4bb5.png)

**Comment by fd00** [comment]
@micwoj92 
Bump to 0.5.0 (WIP)
* https://github.com/fd00/yacp/commit/04e01b4e4edc8286c264257841bcc27c0bce0b0c

Since cygport-0.34.0 does not support autoconf-2.71, you need to apply the latest diff manually.
* https://www.mail-archive.com/cygwin-apps@cygwin.com/msg38399.html

```
$ cd /tmp
$ wget https://crepo.or.cz/cygport/rpm-style.git/blob_plain/refs/heads/to-upstream:/cygclass/autotools.cygclass
$ mv autotools.cygclass /usr/share/cygport/cygclasses
```
