### ISSUE TITLE
Feedback regarding igraph

### ISSUE THREAD

**Issue by szhorvat** [fd00/yacp#33]
Thanks for including [igraph](https://github.com/fd00/yacp/tree/master/igraph) in YACP. I am opening this issue to give feedback on a few minor points.

 - Fortran is not a build dependency. https://github.com/fd00/yacp/blob/master/igraph/README#L32
 - We recommend building from the release tarball, which is https://github.com/igraph/igraph/releases/download/0.9.5/igraph-0.9.5.tar.gz Currently you are using the snapshot of igraph's git repo at the 0.9.5 tag, which is not exactly the same (https://github.com/igraph/igraph/archive/refs/tags/0.9.5.tar.gz). If you use the release tarball, then [this hack](https://github.com/fd00/yacp/blob/master/igraph/igraph-0.9.5-1bl1.cygport#L15) will no longer be necessary, and `flex`/`bison` can be removed from the build dependencies.
 - This line does not do anything at this moment: https://github.com/fd00/yacp/blob/master/igraph/igraph-0.9.5-1bl1.cygport#L24
 - We prefer the styling "igraph" and not "Igraph", even at the beginning of sentences (https://github.com/fd00/yacp/blob/master/igraph/igraph-0.9.5-1bl1.cygport#L6)
 - The website is https://igraph.org/ (https://github.com/fd00/yacp/blob/master/igraph/README#L43)
 - We keep some useful notes for package maintainers here: https://igraph.org/c/html/latest/igraph-Installation.html#igraph-Installation-notes-for-package-maintainers
 - Version 0.9.7 is now available, and contains quite a few bugfixes compared to 0.9.5.

**Comment by fd00** [comment]
Corrected as noted. 
- https://github.com/fd00/yacp/commit/55363ec9d2701cf1b6a74c371d4f4cf3c43b658b

Thank you.
