### ISSUE TITLE
Compiling MFOC & MFCUK on windows, Help Me Please!! 

### ISSUE THREAD

**Issue by hamedsbt** [fd00/yacp#4]
Hello, 
I compiled libnfc 1.7.1 win CMAKE on windows 8.1 and need compile mfoc/mfcuk on windows too, so tried Cygwin and minGW32-make and get same error for both(mfoc & mfcuk)

Cygwin and minGW32-make and Cygport ERROR:

mingw32-make  all-recursive
mingw32-make[1]: Entering directory '/usr/src/mfoc/mfoc-0.10.7-1bl1.x86_64/src/mfoc-0.10.7'
Making all in src
mingw32-make[2]: Entering directory '/usr/src/mfoc/mfoc-0.10.7-1bl1.x86_64/src/mfoc-0.10.7/src'
  CC     crapto1.o
  CC     crypto1.o
  CC     mfoc.o
  CC     mifare.o
  CC     nfc-utils.o
  CCLD   mfoc.exe
/usr/lib/gcc/x86_64-pc-cygwin/4.8.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lnfc
collect2: error: ld returned 1 exit status
Makefile:305: recipe for target 'mfoc.exe' failed
mingw32-make[2]: *** [mfoc.exe] Error 1
mingw32-make[2]: Leaving directory 'D:/mifare1K/_with makefile/mfoc-0.10.7/src'
Makefile:289: recipe for target 'all-recursive' failed
mingw32-make[1]: *** [all-recursive] Error 1
mingw32-make[1]: Leaving directory 'D:/mifare1K/_with makefile/mfoc-0.10.7'
Makefile:229: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

What mean -lnfc? (defined as mfoc_LDADD and libnfc_LIBS in makefile, I guess load library nfc)

After try for many days I encountered this error, it maybe my last error so I'm very interested to bypass it,

HELP ME PLEASE!

**Comment by fd00** [comment]
-lnfc means to link nfs library (need libnfs-devel)

please check build/config.log whether mfoc_LDADD and libnfc_LIBS are defined.

**It seems unrelated to cygwin, I am closing this issue.**
